export { default as LatestNewsA } from './LatestNewsA'
export { default as LatestNewsB } from './LatestNewsB'
export { default as LatestNewsC } from './LatestNewsC'
export { default as LatestNewsD } from './LatestNewsD'
export { default as LatestNewsE } from './LatestNewsE'